WIP: 227 connect idservice to daisy
elixir-luxembourg/daisy pull request #240
Opened 2021-06-08 15:24 UTC by jLebioda

2021-06-10 11:42 UTC, jLebioda commented
What's missing is automatic publishing unpublished Partners/Projects linked to a Dataset - I will add it presently

2021-06-18 11:17 UTC, vildead requested changes
Just parking it here. If you add comments, I can probably fix those:

- [ ] 1. do we need the "Is published?" field in entity editor page? (project/cohort/partner)
- [ ]  At the moment, super user can unpublish the entity by unchecking the checkbox :/ Also this field is very misleading for the users.
- [ ] 2. It's possible to edit "elu_accession" attribute for published datasets (Dataset Editor page) :scream: 
- [x] 3. Corner ribbon "Published" does not show up for published project (entity overview box)
- [ ] 4. When publishing dataset, we could include a modal box with notification that also subentities (cohorts, partners, project, ...) will be published.

2021-06-18 11:17 UTC, vildead commented on web/templates/projects/project.html
> +                                {% comment %}
Just to confirm - this doesn't have to be a comment any more, right? The views are just redirecting without actually doing anything :+1:

2021-06-22 15:26 UTC, jLebioda commented
Will close this PR; this will be merged in #243

2021-06-22 15:26 UTC, closed without merging